-- Club table stake settings for game-server rake enforcement
ALTER TABLE clubs
  ADD COLUMN IF NOT EXISTS rake_cap INTEGER NOT NULL DEFAULT 300,
  ADD COLUMN IF NOT EXISTS no_flop_no_rake BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS min_buy_in INTEGER NOT NULL DEFAULT 4000,
  ADD COLUMN IF NOT EXISTS max_buy_in INTEGER NOT NULL DEFAULT 20000;
